export default {
  accepted: 'check-circle-outline',
  confirmed: 'check-underline-circle',
  loading: 'loading',
  messages: 'email',
  menus: 'silverware-fork-knife',
  wallet: 'wallet',
  profile: 'account-circle',
  rejected: 'close-circle',
  requested: 'clock',
  calendar: 'calendar',
  clock: 'clock-outline',
  guests: 'account-multiple',
  location: 'map-marker-outline',
  money: 'credit-card-outline',
  user: 'account-outline',
  rightArrow: 'chevron-right',
  lock: 'lock-outline',
  logout: 'logout',
  pencil: 'pencil-outline',
  close: 'window-close'
  // requested: 'clock-outline',
  // rejected: 'close-circle-outline',
};
